

<form  class="mb-4" method='POST' action='addEquipo'>
    <div class='form-group'> 
        <label for='nombre'>Nombre</label>
        <input type='text' class='form-control'  name='nombre' required>
    <div class='form-group'>
        <label for='puntos'>Puntos</label>
        <input type='number' class='form-control'  name='puntos' required>
    </div>
    <div class='form-group'>
        <label for='pj'>Partidos Jugados</label>
        <input type='number' class='form-control'  name='pj' required>
    </div>
    <div class='form-group'>
        <label for='pg'>Partidos Ganados</label>
        <input type='number' class='form-control'  name='pg' required>
    </div>
    <div class='form-group'>
        <label for='pe'>Partidos Empatados</label>
        <input type='number' class='form-control'  name='pe' required>
    </div>
    <div class='form-group'>
        <label for='pp'>Partidos Perdidos</label>
        <input type='number' class='form-control'  name='pp' required>
    </div>
    <button type='submit' class='btn btn-primary'>Enviar</button>
</form>

