<form class="mb-4" method='POST' action='<?= BASE_URL?>updateEquipo'>

<div class='form-group'>
    <label for='id_equipo'>id_equipo</label>
    <input type='number' class='form-control' name='id_equipo' readonly value="<?= $equipos->id_equipo ?>"> 
</div>
<div class='form-group'>
    <label for='nombre'>Nombre</label>
    <input type='text' class='form-control' name='nombre' required value="<?= $equipos->nombre ?>">
</div>
<div class='form-group'>
    <label for='puntos'>Puntos</label>
    <input type='number' class='form-control' name='puntos' required value="<?= $equipos->puntos ?>">
</div>
<div class='form-group'>
    <label for='pj'>Partidos Jugados</label>
    <input type='number' class='form-control' name='pj' required value="<?= $equipos->pj ?>">
</div>
<div class='form-group'>
    <label for='pg'>Partidos Ganados</label>
    <input type='number' class='form-control' name='pg' required value="<?= $equipos->pg ?>">
</div>
<div class='form-group'>
    <label for='pe'>Partidos Empatados</label>
    <input type='number' class='form-control' name='pe' required value="<?= $equipos->pe ?>">
</div>
<div class='form-group'>
    <label for='pp'>Partidos Perdidos</label>
    <input type='number' class='form-control' name='pp' required value="<?= $equipos->pp ?>">
</div>
<button type='submit' class='btn btn-primary'>Enviar</button>
</form>
